## Simple RNN

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
#sentences:

sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good']

In [7]:
#define the vocabulary size:

voc_size=10000


In [8]:
#one hot representation

one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[43, 3491, 5974, 9362],
 [43, 3491, 5974, 6577],
 [43, 8324, 5974, 9205],
 [3585, 2108, 1107, 6720, 7068],
 [3585, 2108, 1107, 6720, 9827],
 [8666, 43, 5003, 5974, 8014],
 [9333, 1356, 5987, 6720]]

In [9]:
#word embedding representation:

from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   43 3491 5974 9362]
 [   0    0    0    0   43 3491 5974 6577]
 [   0    0    0    0   43 8324 5974 9205]
 [   0    0    0 3585 2108 1107 6720 7068]
 [   0    0    0 3585 2108 1107 6720 9827]
 [   0    0    0 8666   43 5003 5974 8014]
 [   0    0    0    0 9333 1356 5987 6720]]


In [12]:
#feature representation:

dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [16]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 415ms/step


array([[[ 1.39924921e-02,  4.22340631e-03,  1.16934404e-02,
         -1.73930079e-03, -4.11183015e-02,  1.26356222e-02,
          4.04076651e-03, -3.65747586e-02,  3.69328745e-02,
          2.34153979e-02],
        [ 1.39924921e-02,  4.22340631e-03,  1.16934404e-02,
         -1.73930079e-03, -4.11183015e-02,  1.26356222e-02,
          4.04076651e-03, -3.65747586e-02,  3.69328745e-02,
          2.34153979e-02],
        [ 1.39924921e-02,  4.22340631e-03,  1.16934404e-02,
         -1.73930079e-03, -4.11183015e-02,  1.26356222e-02,
          4.04076651e-03, -3.65747586e-02,  3.69328745e-02,
          2.34153979e-02],
        [ 1.39924921e-02,  4.22340631e-03,  1.16934404e-02,
         -1.73930079e-03, -4.11183015e-02,  1.26356222e-02,
          4.04076651e-03, -3.65747586e-02,  3.69328745e-02,
          2.34153979e-02],
        [-4.74731103e-02,  1.96078084e-02, -1.99639797e-03,
          4.49353792e-02, -2.24661827e-02, -2.69129761e-02,
          2.63993815e-03,  3.29769142e-02, -1.913545

In [17]:
embedded_docs[0]

array([   0,    0,    0,    0,   43, 3491, 5974, 9362])

In [18]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 95ms/step


array([[ 0.01399249,  0.00422341,  0.01169344, -0.0017393 , -0.0411183 ,
         0.01263562,  0.00404077, -0.03657476,  0.03693287,  0.0234154 ],
       [ 0.01399249,  0.00422341,  0.01169344, -0.0017393 , -0.0411183 ,
         0.01263562,  0.00404077, -0.03657476,  0.03693287,  0.0234154 ],
       [ 0.01399249,  0.00422341,  0.01169344, -0.0017393 , -0.0411183 ,
         0.01263562,  0.00404077, -0.03657476,  0.03693287,  0.0234154 ],
       [ 0.01399249,  0.00422341,  0.01169344, -0.0017393 , -0.0411183 ,
         0.01263562,  0.00404077, -0.03657476,  0.03693287,  0.0234154 ],
       [-0.04747311,  0.01960781, -0.0019964 ,  0.04493538, -0.02246618,
        -0.02691298,  0.00263994,  0.03297691, -0.01913545, -0.01786468],
       [-0.03204627,  0.02793482, -0.00741373, -0.01025414,  0.03455124,
        -0.04255481,  0.04224123, -0.04381665, -0.0234216 , -0.00934781],
       [-0.00435957,  0.00223615,  0.02460381, -0.01454604, -0.00744937,
         0.00740846, -0.04421816,  0.03075519